### ISSUE TITLE
Fail to recompile tools when ocaml (and its dependency) needs to be recompiled.

### ISSUE THREAD

**Issue by panglesd** [tarides/ocaml-platform-installer#113]
When (for some reason) the ocaml package need to be recompiled, all of its dependency have also to be. However, since the repository they come from is disabled, they cannot be.

A solution to this would be to pin them with a path, instead of just installing them from the repo.

**Comment by Julow** [comment]
Could there be a way to tell Opam not to recompile ocaml ? It's certainly because a system dependency changed so it's not useful in this case.

**Comment by panglesd** [comment]
Fixed by #134.
