### ISSUE TITLE
Pinned compiler binary package are still put in the cache.

### ISSUE THREAD

**Issue by panglesd** [tarides/ocaml-platform-installer#114]
Indeed, the binary is ultimately installed from the cache. It could overwrite existing binary package and be installed in place of other later...

The solution to this could be:
- Use another temporary binary repo when a pinned compiler is detected, and remove it after
- Do not add them to a repo, but pin those package to the right link instead of installing them through a repo

The second solution could be applied for the installation of all packages, to prevent the problem where `ocaml` needs to be recompiled but the repository where the package comes from has been disabled (reported in #112).

**Comment by Julow** [comment]
Fixed in https://github.com/tarides/ocaml-platform-installer/pull/115
