### ISSUE TITLE
`ocaml-platform --version` tells commit and not tag

### ISSUE THREAD

**Issue by panglesd** [tarides/ocaml-platform-installer#125]
It is easier for a user to know the version if it's the version and not the commit hash.

**Comment by Julow** [comment]
This comes from not using simple tags instead of annotated tags (`git tag -a`). `dune subst` calls `git describe`, which only look at annotated tags.

**Comment by panglesd** [comment]
Release 0.7.0 was created with #60 merged, yet it stills give `4752249` instead of `0.7.0`.

I tried running the release script at home and it seems to work (`--version` gives `0.7.0`).

**Comment by samoht** [comment]
The tool currently returnss something even less useful:

```
❯ bash < <(curl -sL https://github.com/tarides/ocaml-platform-installer/releases/latest/download/installer.sh)

=> Download ocaml-platform-0.7.0-macos-arm64.tar
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 3949k  100 3949k    0     0  12.1M      0 --:--:-- --:--:-- --:--:-- 42.5M
=> Install into /usr/local/bin
Installation is done. Please run 'ocaml-platform' to install the Platform tools inside your set switch.

❯ ocaml-platform  --version
%%VERSION%%
```

**Comment by panglesd** [comment]
On `macos-arm64`, the release is not done through the github CI (until [support](https://github.com/actions/runner-images/issues/2187) is added or we change our releasing process). A `dune subst` must have been forgotten @tmattio
