### ISSUE TITLE
Wrong version of ocamlformat selected

### ISSUE THREAD

**Issue by samoht** [tarides/ocaml-platform-installer#126]
If ocamlformat is already available in the current environment, `ocaml-platform` doesn't seem to check if the version corresponds:

```
❯ bash < <(curl -sL https://github.com/tarides/ocaml-platform-installer/releases/latest/download/installer.sh)

=> Download ocaml-platform-0.6.0-macos-arm64.tar
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 3929k  100 3929k    0     0  2587k      0  0:00:01  0:00:01 --:--:-- 5837k
=> Install into /usr/local/bin
Password:
Installation is done. Please run 'ocaml-platform' to install the Platform tools inside your set switch.
❯ ocaml-platform
* Inferring tools version...
  -> dune is already installed
  -> dune-release is already installed
  -> merlin is already installed
  -> ocaml-lsp-server.1.10.5 will be installed from cache
  -> odoc is already installed
  -> ocamlformat is already installed
* Installing tools...
  -> The tools have been installed. For more information on the platform tools, run `ocaml-platform --help`
* Success.
❯ ocamlformat --version
0.23.0
❯ head .ocamlformat
version = 0.24.1
profile = conventional

break-infix = fit-or-vertical
parse-docstrings = true
```

**Comment by panglesd** [comment]
One of the current property of `ocaml-platform` is that it never changes anything in the switch, apart from installing (or updating) zero-dependencies "platform" package.

In your case, the "true" `ocamlformat` (which differs with the platform one as it includes a library), was installed in the switch. Therefore, `ocaml-platform` does not want to replace it with the platform version, even with another specified version (maybe, other packages in the switch depend on the ocamlformat library).

If you had installed `ocamlformat` with the platform in the first place, then changed your `.ocamlformat` file, then `ocamlformat` would have been replaced to match the version.

I would be keen on keeping the behaviour of never modifying user-installed packages, even if that would make sense most of the time in this case (I don't know how many libraries depend on `ocamlformat` as a libraries but at least [some](https://github.com/ocaml-ppx/ocamlformat/issues/2053)).

**Comment by Julow** [comment]
I don't think that's a useful property. It prevents the installer from doing what we expect from it in order to save a niche usecase.
I don't think many people are using ocamlformat's library (it's not easy to use) and I don't think it's a encouraged thing to do (there's no `ocamlformat-lib` package) but that's beside the point.
Virtually everyone has ocamlformat installed in their switch. It is the only documented workflow with Opam and OCamlformat seems popular.

**Comment by Julow** [comment]
According to an offline discussion, I merged the fix for this issue.
