### ISSUE TITLE
Add a versioning mechanism for cache

### ISSUE THREAD

**Issue by panglesd** [tarides/ocaml-platform-installer#131]
Currently, there is no way to know which packages have been created with which version of the tool.
This poses some problems when a new version fixes a bug in the package generation, or changes how they should be.

For instance:
- If we go the #128 way, we might have to rename packages tools from `<tool-name>+bin+platform` to `<tool-name>`. But that would be a pity to lose all cached packages.
- The way we create and expect to be the packages for sandbox compiler might change. Not updating them would create issues such as #130.

We should add a versioning mechanism for those packages.

**Comment by Julow** [comment]
The two issues should be fixed now.
