### ISSUE TITLE
Error when using the Platform Installer on Debian

### ISSUE THREAD

**Issue by e10e3** [tarides/ocaml-platform-installer#156]
Hello, I encountered an error when using the Platform Installer.

I am using Debian 11.
I installed Opam with the distribution's package, then tried using the Platform Installer.

After successfully executing `install-platform.sh`, running `ocaml-platform` yielded this output: 
```
* Initialising Opam before the first use, this might take some time...
Initting repo
* Inferring tools version...
  -> dune.3.7.1 will be built from source
  -> dune-release.1.6.2 will be built from source
  -> merlin.4.8-500 will be built from source
  -> ocaml-lsp-server.1.15.1-5.0 will be built from source
  -> odoc.2.2.0 will be built from source
  -> ocamlformat.0.25.1 will be built from source
* Building the tools...
  -> Creating a sandbox...
  -> [1/6] Building ocamlformat...
  -> [2/6] Building odoc...
  -> [3/6] Building ocaml-lsp-server...
  -> [4/6] Building merlin...
  -> [5/6] Building dune-release...
  -> [6/6] Building dune...
* Installing tools...
ocaml-platform: [ERROR] Command 'opam install dune.3.7.1-ocaml5.0.0+platform
           dune-release.1.6.2+platform merlin.4.8-500-ocaml5.0.0+platform
           ocaml-lsp-server.1.15.1-5.0-ocaml5.0.0+platform
           odoc.2.2.0-ocaml5.0.0+platform ocamlformat.0.25.1+platform --yes
           -q --color=never --root /home/<user>/.opam' failed: exited with 40
```

Please let me know if you need further information.

**Comment by e10e3** [comment]
My version of Opam is 2.0.8.

Running `ocaml-platform` again gives me the same error, but without the building step:
```
Initting repo
* Inferring tools version...
  -> dune.3.7.1 will be installed from cache
  -> dune-release.1.6.2 will be installed from cache
  -> merlin.4.8-500 will be installed from cache
  -> ocaml-lsp-server.1.15.1-5.0 will be installed from cache
  -> odoc.2.2.0 will be installed from cache
  -> ocamlformat.0.25.1 will be installed from cache
* Installing tools...
ocaml-platform: [ERROR] Command 'opam install ocamlformat.0.25.1+platform
           odoc.2.2.0-ocaml5.0.0+platform
           ocaml-lsp-server.1.15.1-5.0-ocaml5.0.0+platform
           merlin.4.8-500-ocaml5.0.0+platform dune-release.1.6.2+platform
           dune.3.7.1-ocaml5.0.0+platform --yes -q --color=never --root
           /home/<user>/.opam' failed: exited with 40
```

**Comment by e10e3** [comment]
Here is the contents of the opam file for one of the packages:
```sh
$ cat ~/.opam/plugins/ocaml-platform/cache/repo/packages/odoc/odoc.2.2.0-ocaml5.0.0+platform/opam 
opam-version: "2.0"
name: "odoc"
depends: [
  "ocaml-system" {= "5.0.0"} | "ocaml-variants" {= "5.0.0"} |
  "ocaml-base-compiler" {= "5.0.0"}
]
available: arch = "x86_64" & os-distribution = "debian"
url {
  src:
    "/home/<user>/.opam/plugins/ocaml-platform/cache/archives/odoc.2.2.0-ocaml5.0.0+platform.tar.gz"

``` 

The local archive is indeed where indicated:
```
$ ls ~/.opam/plugins/ocaml-platform/cache/archives/
dune.3.7.1-ocaml5.0.0+platform.tar.gz
dune-release.1.6.2+platform.tar.gz
merlin.4.8-500-ocaml5.0.0+platform.tar.gz
ocamlformat.0.25.1+platform.tar.gz
ocaml-lsp-server.1.15.1-5.0-ocaml5.0.0+platform.tar.gz
odoc.2.2.0-ocaml5.0.0+platform.tar.gz
```

As you can see, I have similar results to yours.

After wiping the cache by deleting `~/.opam/plugins/ocaml-platform`, `ocaml-platform` indeed recompiled the binaries for the tools, but the installation failed in the same way as before, with the same error output.

**Comment by panglesd** [comment]
What's happening is really strange!

Could you install one of the platform package directly with opam?
```
$ opam install ocamlformat.0.25.1+platform -vv
```
and report the result? (And if `-vv` is not enough, maybe try `-vvv`?)

**Comment by panglesd** [comment]
I'm glad I was able to help!

Indeed, `rsync` is missing from the in-text list of dependencies. I will add it (the exact list of dependencies we should mention has never been very clear, see https://github.com/tarides/ocaml-platform-installer/pull/84#discussion_r961734398 and #120)

I will also open an issue on ocaml.org.

One issue that remains is that `opam`'s error message was not included in `ocaml-platform`'s message. I'll have to check why, I though it was supposed to be included.

**Comment by e10e3** [comment]
The problem is not present on [ocaml.org](https://ocaml.org) any more.
I'll close the issue.
