### ISSUE TITLE
Define the current state of the OCaml Platform

### ISSUE THREAD

**Issue by pitag-ha** [tarides/ocaml-platform-installer#19]
`ocaml-platform` is meant to be the installer for the [OCaml Platform](https://ocaml.org/docs/platform). We need to make sure that the set of tools in the OCaml Platform is perceived as coherent on two levels: first, it needs to be intrinsically coherent; and second, it needs to be coherent with the set of tools installed by `ocaml-platform`.

With "intrinsically coherent" I mean that the choice of tools inside the OCaml Platform and the way they're placed into the four different categories of the OCaml Platform is coherent. For example, with the current choice, I myself would ask: why are `bun` and `mdx` in the OCaml Platform, while e.g. the `js_of_ocaml` compiler and `bisect_ppx` aren't?

With "coherent with the set of tools installed by `ocaml-platform`", I simply mean that we need to choose which categories of the OCaml Platform we want to be covered by `ocaml-platform`. Let's say that's only the active tools. Then, we need to make sure that we can explain very well any possible exception to the 1-1 correspondence between the active OCaml Platform tools and the tools installed by `ocaml-platform`.

## "Intrinsical" coherency

What's the reason why the _current state_ of the OCaml Platform is the way it is?

### General rules

In [the video on the OCaml Platform site](https://ocaml.org/docs/platform), avsm points out clear necessary rules for projects to form part of the OCaml Platform:

- only tools should be in the Platform (no libraries), at least for now
- characteristics a tool needs to fulfil to be a fit for the OCaml Platform are:
   - it improves the OCaml development process
   - it's actively maintained: there's a strategy for incremental changes and a guarantee of backwards compatibility over the upcoming years
   - it's liberally licensed
   - it assists with the reuse and publication of OCaml code (btw, how is that different from liberally licensed?)
   - it has a minimum number of users (no concrete number though)
   - it has maintainers in the community
   - it's open to any contributor

- tools inside the Platform shouldn't be duplicated; i.e. there shouldn't be two tools inside the `active` category of the Platform serving the same purpose

I think that's a good basis for how to shape the Platform in the future. The question in this issue is where the "initial"/current state of the Platform comes from though.(*)

### Defining the current/initial state

Back to the question above: Is there a rule/description/definition/explanation that corresponds to the _current state_ of the OCaml Platform? I think we'll need to come up with something very simple and then adapt the OCaml Platform to it (not the other way around).

#### The set of tools inside the current/initial state

What about keeping the initial state as minimal as possible? Concretely, what about the following?

> The initial state of the Platform contains all tools that fulfil the rules above and that serve a purpose that needs to be served to keep OCaml a real-world language.

An ok practical rule of thumb to find out if a tool "serves a purpose that needs to be served to keep OCaml a real-world language",  could be: is the tool important enough to be considered by the ocaml-release-readiness(**)? Of course, that rule of thumb doesn't _directly_ capture tools like `opam` or `dune-release`/`opam-publish` since they're automatically compiler-forward-compatible, but I do think it _indirectly_ captures those tools: if those tools weren't automatically compiler-forward-compatible, they'd definitely be included into the ocaml-release-readiness efforts.

If we followed that rule, I think we'd have to remove exactly `mdx` and `bun` from the Platform and wouldn't need to add anything to the Platform.

#### The categories inside the current/initial state

If we follow the description above (only having really important tools in the Platform), I think for the initial state, it would make sense not to have any tools in the category of `sustained` tools at all at the beginning. So I'd say, we could simply promote all tools from `incubate` to `active`.

### Coherency between the OCaml Platform and `ocaml-platform`

I think we can leave this part for later tbh. We should have an intrinsically coherent OCaml Platform and then `ocaml-platform` should install all `active` (or whatever categories we agree on) tools in the Platform, unless there's a good reason for a tool not to be installed by  `ocaml-platform`.

## Questions

I've just stated a couple of things that are probably controversial. So some questions:

1. First of all, do people agree that it's important to develop and discuss a good rule/description/definition/explanation for the initial state of the Platform (or do you think it's just the initial state, so it doesn't really matter too much what to put in there, since the Platform will get shaped well later)?
2. What do you think about the restrictive condition for the initial state I've proposed?
    > The initial state of the Platform contains all tools that fulfil the rules above and that serve a purpose that needs to be served to keep OCaml a real-world language.
3. Do you agree that with that restrictive condition, we'd remove exactly `mdx` and `bun` from the Platform and wouldn't add anything to it?
4. Does it sound both good and coherent to have an empty `incubate` category for the initial state?

## Difference to the current plan

The proposed changes in our current [docs section](https://github.com/tarides/ocaml-platform/blob/main/doc/state.md) are (I'm just copying and pasting now):

-    Remove ppxlib from the Platform
-    Remove Bun from the Platform
-    Promote ocaml-lsp to Active
-    Promote odoc to Active
-    Promote mdx to Active
-    Promote ocamlformat to Active
-    Promote opam-publish to Sustain
-    Promote dune-release to Active

I first tried to come up with a justification for those proposed changes, but then figured it would be better to do it the other way around: first define a good rule/description/definition/explanation for the initial state of the Platform and then propose changes to match that definition. That has led to my proposed changes above: remove exactly `mdx` and `bun` from the Platform. By the way, my thoughts about `dune-release` <-> ` opam-publish` aren't covered in this issue since that's another topic; I'll open another issue for that. So the differences between those proposed changes and my proposed changes are:

- I probably wouldn't remove `ppxlib` from the Platform (in which case I'd promote it to Active), but I'd discuss that in a separate issue
- Instead of promoing `mdx` to Active, I'd remove it from the platform. Again: I'd discuss that in a separate issue
- I wouldn't simply state that we should promote `dune-release` to Active and move `opam-publish` to Sustain; instead, I'd discuss their co-existence (in a separate issue)

---------------------------------

(*) By "initial state", I mean the following: The idea is to make the OCaml Platform a community project, where any community member can suggest to add a new project to the platform. Once we're there (🤞), the set of rules above will serve as a good basis for discussions on whether a project should be added to the Platform or change category in there.

(**) With the "ocaml-release-readiness" I'm referring to all the work that's being done to orchestrate new compiler releases, making sure that all important tools, that won't automatically support the new compiler, will do so on time for the release.

**Comment by tmattio** [comment]
Done in https://github.com/ocaml/ocaml.org/pull/571
