### ISSUE TITLE
Should `ppxlib` be in the OCaml Platform?

### ISSUE THREAD

**Issue by pitag-ha** [tarides/ocaml-platform-installer#20]
As pointed out in https://github.com/tarides/ocaml-platform/issues/19 (particularly in **Difference to the current plan**), there are different opinions on the question if `ppxlib` should be in the Platform or not. Maybe we can discuss that here on the issue? I've explained in **Defining the current/initial state** of https://github.com/tarides/ocaml-platform/issues/19 why, without knowing the counterarguments for `ppxlib` being in the OCaml, I think it should be in the Platform.

What are the counterarguments for `ppxlib` being in the Platform? Is the counterargument that `ppxlib` -among others- is a library? If so: I see `ppxlib` as a tool set that provides everything needed for meta-programming in OCaml. Of course, that also includes a library to write ppx rewriters, but it also includes the `ppxlib` driver, which is a tool. Do you agree?

Or is it because `ppxlib` can't be generally installed by `ocaml-platform`? In that case, we should discuss if we want `ocaml-platform` to be the base for deciding which tools are in the OCaml Platform or if we want to define and shape the OCaml Platform and write `ocaml-platform` to consolidate the OCaml Platform whereever it makes sense.

@tmattio, what are your reasons to remove `ppxlib` from the Platform? Do you agree with https://github.com/tarides/ocaml-platform/issues/19 in general?

**Comment by panglesd** [comment]
Closed by https://github.com/ocaml/ocaml.org/pull/563 (ppxlib is no longer in the platform (only binaries go in there) but has its own guide in the official website).
