### ISSUE TITLE
Expose a CLIs for all/most platform tools in `ocaml-platform` (?)

### ISSUE THREAD

**Issue by pitag-ha** [tarides/ocaml-platform-installer#25]
Of course this isn't a short-term or even medium-term issue, but I think that for some people, particularly for @tmattio, this is still the longer term final goal, so I think it's good to have an issue for it.

Of course, if this is feasible, it would mean an incredible improvement in user experience, so it would be worth overcoming some issues for it, both technical and non-technical. But still, I think there are quite a few quite significant issues with it, so I also think it's important to discuss them before getting back to the idea.

### Technical issues

Of course, to start with there are all the technical issues [we had last time](https://github.com/tarides/ocaml-platform/blob/main/doc/embedding.md).

But also, unless I'm missing something (in that case, please let me know!), every tool using the compiler's `Marchal` module would only work on the same compiler `ocaml-platform` was compiled with. That would at least include `merlin`, `ocaml-lsp-server`, `odoc` and `ocamlformat` I think. Is that right or am I missing something? If that's right: How would we solve that? Would we only expose a CLI for the tools that don't use the `Marchal` module (I think for me that would be an ok-ish compromise)? Or would we be ok with `ocaml-platform` only supporting one compiler? I think that would mean a hard pay-off for increased user experience, particularly taking into account two things: one, we're in the middle of a major compiler release, so there will probably keep on existing projects only working on the 4.x compiler for some time; and two, we'd need to really make sure to have a very good update story for `ocaml-platform` itself.

And then there are a few more general fat binary downsides we at least need to consider such as having a fat binary will probably slow down starting the servers of some tools.

_Edit:_ Another technical issue that we've now come across trying to embed the `opam` CLI is: if the user has installed another version of `opam` than the version whose library we're embedding, `opam` will notice that and fail.

### Practical issues

Who would maintain such a huge CLI? Would we invite a maintainer of every platform tool to co-maintain `ocaml-platform` (and possibly to duplicate their work by maintaing both their CLI and our CLI)? Or would we ask the platform tool maintainers to port their CLI to `Cmdliner` (if that isn't done already) and expose it? I think the latter might not be possible for all tools (but with that we're getting into _technical_ issues again...).

**Comment by tmattio** [comment]
This is a non goal for the installer.
