### ISSUE TITLE
Packages install opam optimisation

### ISSUE THREAD

**Issue by rjbou** [tarides/ocaml-platform-installer#48]
Generated opam files contains
```
install: [
         [ "cp""-pPR"".""%{prefix}%" ]
         ]
```
In opam 2.1, there is an optimisation of install directory tracking (to record changes for removal), https://github.com/ocaml/opam/pull/4494: if there is an install file and no install command, no tracking is done: recorded changes are the one in the [install](https://opam.ocaml.org/doc/Manual.html#lt-pkgname-gt-install) file.

**Comment by panglesd** [comment]
Thanks for this helpful issue! It was implemented in #73.
