### ISSUE TITLE
`opam config var` is deprecated

### ISSUE THREAD

**Issue by Julow** [tarides/ocaml-platform-installer#61]
Related to https://github.com/tarides/ocaml-platform/issues/50

Opam 2.1 deprecates `opam config` and its sub-commands related to variable in favor of `opam var`.

Potential solutions are:
- Define a version of the CLI, https://github.com/tarides/ocaml-platform/issues/50
- Check Opam's version and handle the two forms
- Use Opam's library. Note: this is a read-write operation, there might be compatibility problems here too.

**Comment by panglesd** [comment]
Closed by #92.
