### ISSUE TITLE
Show simple summary of tools installed

### ISSUE THREAD

**Issue by metanivek** [tarides/ocaml-platform-installer#72]
A summary of tool/version information that `ocaml-platform` manages would give at least two benefits to users of the installer:

1. Confidence in the installer
2. Understanding of which tools are managed by the installer

**Comment by panglesd** [comment]
Thanks a lot for your report!
I agree with you. Would #57 solve this issue? The amount of information given by the log is exactly the same as it was in verbose mode, but more organized. Here is a recording of the logs:
[![asciicast](https://asciinema.org/a/JCMnntcB0TShrTBAwYXleACpt.svg)](https://asciinema.org/a/JCMnntcB0TShrTBAwYXleACpt)

**Comment by panglesd** [comment]
Closed by #57.
